[package]
name = "borealis"
version = "0.3.0"
edition = "2021"
authors = ["AVISI Research Group"]
description = "Sail frontend for GenSim"

[dependencies]
common = { path = "../common" }
sailrs = { path = "../sailrs" }

displaydoc = "0.2.5"
thiserror = "1.0.63"
errctx = "1.0.0"
color-eyre = { version = "0.6.3", default-features = false }
pretty_assertions = "1.4.0"
pretty_env_logger = "0.5.0"
log = "0.4.22"
clap = { version = "4.5.9", features = ["derive"] }
deepsize = "0.2.0"
serde_json = "1.0.120"
num-bigint = { version = "0.4.6", features = ["serde"] }
once_cell = "1.19.0"
regex = "1.10.5"
dot = "0.1.4"
itertools = "0.13.0"
kinded = "0.3.0"
quote = "1.0.36"
syn = { version = "2.0.71",  features = ["full", "parsing"] }
prettyplease = "0.2.20"
proc-macro2 = "1.0.86"
memmap2 = "0.9.4"
rkyv = {version = "0.7.44", default-features = false, features = ["std", "alloc", "size_64"] }
parking_lot = "0.12.3"
cargo-util-schemas = "0.3.1"
toml = "0.8.15"
semver = { version = "1.0.23", features = ["serde"] }
walkdir = "2.5.0"
rayon = "1.10.0"
dashmap = { version = "6.0.1", features = ["rayon"] }
num-rational = { version = "0.4.2", default-features = false }
num-traits = { version = "0.2.19", default-features = false, features = ["i128"] }
