[package]
name = "proc_macro_lib"
version = "0.1.0"
edition = "2024"

[lib]
name = "proc_macro_lib"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = { version = "2.0.101", features = ["extra-traits"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
